in_dir: /home/q359zhan/olinked/data/ethcd/heart/test
out_dir: /home/q359zhan/olinked/data/ethcd/heart/test
out_put_file:  heart-y4-inference-score.csv
model_path: save/pglyco-ethcd-simple.pt
mass_diff_threshold: 0.02
working_dir: null

mode: ethcd

model:
  hidden_size: 768
  num_layers: 6
  dropout_rate: 0
  n_head: 12
  n_head_per_mass_decoder: 12
  decoder_dropout_rate: 0
  max_charge: 1

train:
  lr: 1e-5
  lrZ: 1e-2
  total_epoch: 10
  detect_period: 400
  eval_period: 4000
  weight_decay: 0.01
  epsilon_fulllen_probability: 1
  sample_iteration: 3
  sample_step: 4
  gamma: 0.99
  EPS_START: 0.9
  EPS_END: 0.5
  EPS_DECAY: 1000

sample:
  bin_boarders: [0, 64, 128, 256, 512, 756, 1024, 2048]
  bin_batch_size: [256, 256, 256, 128, 128, 128, 128]

data:
  peptide_max_len: 32

inference:
  beam_size: 9
  mass_cand: "0,1,2,3,4"
  enzyme: KR
  miss_cleavaged: 2
  isotope: "0"
  ms1_threshold: 5
  ms1_threshold_unit: ppm
  ms2_threshold: 0.02
  ms2_threshold_unit: Th

mgf_preprocess:
  glob_pattern: "*.mgf"
  cluster_parquet: cluster.csv.parquet
  fasta: /home/q359zhan/olinked/data/ethcd/heart/mouse_peptides.txt
  pep_csv: null
  sig_mz: [138.055, 144.065, 168.066, 186.076, 204.087, 274.092, 292.103, 366.139]
  ppm_tol: 20.0
  min_rel_intensity: 0.01

fdr:
  output: heart-y4-inference-fdr.csv
  fdr_threshold: 0.01
